name: Release to Stage

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get the latest commit hash
      id: get_commit
      run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Create and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="v$(date +'%y%m%d-%H%M')"
        git tag $TAG_NAME $commit
        git push origin $TAG_NAME
