name: Release to Production

on:
  release:
    types:
      - published
  repository_dispatch:
    types: [trigger-release]
  workflow_dispatch:

jobs:
  reset_release_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
