name: Trigger Milestone Enforcement Rechecks

on:
  milestone:
    types: [created, edited, deleted, closed, opened]

jobs:
  trigger-milestone-checks:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Rerun Milestone Enforcement Checks
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo;
            
            // Fetch open pull requests
            const openPrs = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open'
            });

            // Workflow name to target
            const workflowFileName = 'check-milestone.yml';

            for (const pr of openPrs.data) {
              try {
                // Find recent workflow runs for this PR
                const runs = await github.rest.actions.listWorkflowRuns({
                  owner,
                  repo,
                  workflow_id: workflowFileName,
                  branch: pr.head.ref,
                  event: 'pull_request',
                  per_page: 5 // Limit to recent runs
                });

                // Find the most recent run for this PR
                const prRun = runs.data.workflow_runs.find(run => 
                  run.pull_requests.some(prInfo => prInfo.number === pr.number)
                );

                // If a run is found, rerun it
                if (prRun) {
                  await github.rest.actions.reRunWorkflow({
                    owner,
                    repo,
                    run_id: prRun.id
                  });

                  console.log(`Reran workflow check for PR #${pr.number}`);
                } else {
                  console.log(`No recent workflow run found for PR #${pr.number}`);
                }
              } catch (error) {
                console.error(`Failed to rerun workflow for PR #${pr.number}:`, error);
              }
            }
